# Stage 1 — build
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -q
COPY src ./src
RUN mvn package -DskipTests -q


# # Stage 2 — run
# FROM eclipse-temurin:17-jre-jammy
# WORKDIR /app
# COPY --from=build /app/target/*.jar app.jar
# EXPOSE 8082
# ENTRYPOINT ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "app.jar"]

# Stage 2 — run
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]